// ExcelCopyData.cs
// This class provides methods for all Excel file manipulations, including copying data,
// filtering, and performing calculations. It uses the EPPlus library.
// This version has been fully refactored for readability, maintainability, and resilience.
// It uses descriptive regions, comprehensive XML documentation, and detailed inline comments.
// All logic remains functionally identical to the previous version.

#region Using Directives
// System-related namespaces for core functionalities.
// Third-party namespaces for external libraries.
using Microsoft.Extensions.Configuration;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using OfficeOpenXml.Table.PivotTable;
// Project-specific namespaces for application components.
using QuoteConversionReportAutomation.Configuration;
using QuoteConversionReportAutomation.Helpers;
using QuoteConversionReportAutomation.Interfaces;
using QuoteConversionReportAutomation.Models;
using QuoteConversionReportAutomation.Models.Status;
using QuoteConversionReportAutomation.Orchestrators;
using QuoteConversionReportAutomation.Services.Logging;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
#endregion

namespace QuoteConversionReportAutomation.Services.Excel
{
    /// <summary>
    /// Provides methods for processing and manipulating Excel files using the EPPlus library.
    /// This class is responsible for tasks such as copying data from a source report to a template,
    /// applying filters, triggering calculations, and generating specialised analysis sheets.
    /// It is designed to be robust against changes in column order by mapping headers at runtime.
    /// </summary>
    public class ExcelCopyData
    {
        #region Fields

        /// <summary>
        /// Provides read-only access to the application's configuration settings
        /// from sources like 'appsettings.json'.
        /// </summary>
        private readonly IConfiguration _configuration;

        /// <summary>
        /// The centralised service for managing and broadcasting application-wide status messages
        /// to the user interface.
        /// </summary>
        private readonly IStatusManagerService _statusManager;

        #endregion

        #region Constructor

        /// <summary>
        /// Initialises a new instance of the <see cref="ExcelCopyData"/> class.
        /// </summary>
        /// <param name="configuration">
        /// The application's configuration settings, injected via dependency injection.
        /// Used to retrieve operational parameters like sheet names and file paths.
        /// </param>
        /// <param name="statusManager">
        /// The centralised service for status reporting, injected via dependency injection.
        /// Used to provide real-time feedback to the user during long-running operations.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if the <paramref name="configuration"/> or <paramref name="statusManager"/> is null.
        /// </exception>
        public ExcelCopyData(IConfiguration configuration, IStatusManagerService statusManager)
        {
            // Assign injected dependencies to private fields.
            this._configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
            this._statusManager = statusManager ?? throw new ArgumentNullException(nameof(statusManager));

            // Set the license context for the EPPlus library. This is required for non-commercial use.
            ExcelPackage.License.SetNonCommercialPersonal("Harlow");

            // Log that the instance has been successfully created.
            Logger.LogTrace("ExcelCopyData instance created and EPPlus license context set.");
        }

        #endregion

        #region Public Methods

        /// <summary>
        /// Asynchronously processes a raw Excel report. This is the main public entry point for this class.
        /// It orchestrates copying data from a source file to a template, performing filtering,
        /// running calculations, and saving the final processed report.
        /// </summary>
        /// <param name="selectedFinYear">The financial year string (e.g., "2023_24") relevant for the report.</param>
        /// <param name="reportType">The type of report being processed, which dictates specific logic.</param>
        /// <param name="sourceFilePath">The full path to the raw source Excel file generated by Crystal Reports.</param>
        /// <param name="sourceSheetNameConfigKey">The configuration key for the name of the sheet in the source file.</param>
        /// <param name="baseFileSaveLocation">The base directory where the final processed report will be saved.</param>
        /// <param name="templateFilePath">The full path to the Excel template file that will be used.</param>
        /// <param name="destinationDataSheetNameConfigKey">The configuration key for the name of the sheet in the template where data is copied.</param>
        /// <param name="startRow">The starting row (1-based) in the source sheet from which to begin copying data.</param>
        /// <param name="startCol">The starting column (1-based) in the source sheet from which to begin copying data.</param>
        /// <param name="reportDate">The primary date for the report, used for filename generation and internal logic.</param>
        /// <param name="manualParams">Optional parameters for a manually triggered report, for additional context.</param>
        /// <param name="autoRunDef">Optional definition for an automatically triggered report.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests from the user.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result is the full path to the
        /// final processed Excel file, or null if the processing fails or is cancelled.
        /// </returns>
        public async Task<string?> ProcessExcelReportAsync(
            string selectedFinYear,
            ReportType reportType,
            string sourceFilePath,
            string sourceSheetNameConfigKey,
            string baseFileSaveLocation,
            string templateFilePath,
            string destinationDataSheetNameConfigKey,
            int startRow = 1,
            int startCol = 1,
            DateTime reportDate = default,
            ManualReportParameters? manualParams = null,
            AutoReportDefinition? autoRunDef = null,
            CancellationToken cancellationToken = default)
        {
            // Start a stopwatch to measure the duration of the entire operation.
            var stopwatch = Stopwatch.StartNew();
            Logger.LogTrace($"Entering ProcessExcelReportAsync. ReportType: {reportType}, Source: {sourceFilePath}");

            // Validate that all required string parameters are not null or empty.
            ArgumentException.ThrowIfNullOrEmpty(sourceFilePath, nameof(sourceFilePath));
            ArgumentException.ThrowIfNullOrEmpty(sourceSheetNameConfigKey, nameof(sourceSheetNameConfigKey));
            ArgumentException.ThrowIfNullOrEmpty(baseFileSaveLocation, nameof(baseFileSaveLocation));
            ArgumentException.ThrowIfNullOrEmpty(templateFilePath, nameof(templateFilePath));
            ArgumentException.ThrowIfNullOrEmpty(destinationDataSheetNameConfigKey, nameof(destinationDataSheetNameConfigKey));

            // Retrieve sheet names from the application configuration.
            string sourceSheetName = _configuration.GetValue<string>($"OperationalParameters:ExcelSheetNames:{sourceSheetNameConfigKey}", "Sheet1")!;
            string destinationDataSheetName = _configuration.GetValue<string>($"OperationalParameters:ExcelSheetNames:{destinationDataSheetNameConfigKey}", "DATA")!;
            string analysisSheetName = _configuration.GetValue<string>("OperationalParameters:ExcelSheetNames:TemplateAnalysisSheet", "Analysis")!;

            // Ensure the financial year is provided for report types that require it.
            if (reportType is ReportType.Weekly or ReportType.Daily or ReportType.Daily5Day1k)
            {
                ArgumentException.ThrowIfNullOrEmpty(selectedFinYear, nameof(selectedFinYear));
            }

            // Default the report date to today if not specified for a non-custom report.
            if (reportDate == default && reportType != ReportType.Custom)
            {
                reportDate = DateTime.Today;
                Logger.LogWarning($"reportDate not specified for non-custom report. Defaulting to Today for filename: {reportDate:yyyy-MM-dd}");
            }

            // Declare variables for file paths to be used within the try block.
            string? finalFilePath = null;
            string? tempFilePath = null;

            try
            {
                // Post an initial status message to the UI.
                _statusManager.Post("Starting Excel processing...", MessageType.InProgress);
                cancellationToken.ThrowIfCancellationRequested();

                // 1. Determine and create the report-specific output folder.
                DateTime folderTimestampDate = reportType == ReportType.Custom ? DateTime.Now : reportDate;
                string? fullOutputFolderPath = FolderCreation.CreateReportSpecificFolder(reportType, baseFileSaveLocation, folderTimestampDate, _configuration);
                if (string.IsNullOrEmpty(fullOutputFolderPath))
                {
                    throw new InvalidOperationException("Failed to create or determine the report output folder.");
                }
                _statusManager.Post("Output folder prepared.", MessageType.InProgress);
                cancellationToken.ThrowIfCancellationRequested();

                // 2. Define a path for a temporary working copy of the template file. Using a GUID ensures uniqueness.
                tempFilePath = Path.Combine(fullOutputFolderPath, $"temp_processing_{Guid.NewGuid()}.xlsx");
                Logger.LogDebug($"Using temporary file: {tempFilePath}");

                // 3. Copy the template to the temporary location to avoid modifying the original template.
                if (!File.Exists(templateFilePath))
                {
                    throw new FileNotFoundException($"Excel template file not found: {templateFilePath}", templateFilePath);
                }
                await Task.Run(() => File.Copy(templateFilePath, tempFilePath, true), cancellationToken);
                _statusManager.Post("Template copied.", MessageType.InProgress);
                cancellationToken.ThrowIfCancellationRequested();

                // 4. Open the source and destination Excel packages and perform the main processing.
                _statusManager.Post("Opening Excel files for processing...", MessageType.InProgress);
                if (!File.Exists(sourceFilePath))
                {
                    throw new FileNotFoundException($"Raw source data file not found: {sourceFilePath}", sourceFilePath);
                }

                // The 'using' statements ensure that the Excel packages are properly disposed of.
                using (var sourcePackage = new ExcelPackage(new FileInfo(sourceFilePath)))
                using (var destinationPackage = new ExcelPackage(new FileInfo(tempFilePath)))
                {
                    // Get the source worksheet from the raw data file.
                    ExcelWorksheet? sourceWorksheet = sourcePackage.Workbook.Worksheets[sourceSheetName];
                    if (sourceWorksheet == null)
                    {
                        throw new FileNotFoundException($"Source sheet '{sourceSheetName}' not found in source file '{sourceFilePath}'.");
                    }

                    // Get or create the destination 'DATA' sheet in our temporary template copy.
                    ExcelWorksheet destinationDataWorksheet = GetOrCreateDestinationWorksheet(destinationPackage, destinationDataSheetName, sourceWorksheet);

                    // Map column headers to indices for robust processing. This is a key part of the refactoring.
                    var dataColumnMap = MapColumnIndices(destinationDataWorksheet, 1, new[] { "Customer", "Price", "Posting Code" });
                    ExcelWorksheet analysisSheet = destinationPackage.Workbook.Worksheets[analysisSheetName] ?? throw new InvalidOperationException($"Analysis sheet '{analysisSheetName}' not found.");
                    var analysisColumnMap = MapColumnIndices(analysisSheet, 5, new[] { "Customer", "Number of Estimates", "SOURCE FILE", "CONVERTED DATE", "FY" });

                    // Get the dimensions of the source data.
                    int sourceRowCount = sourceWorksheet.Dimension?.Rows ?? 0;
                    int sourceColCount = sourceWorksheet.Dimension?.Columns ?? 0;

                    // Copy the raw data from the source file to the 'DATA' sheet in the template.
                    _statusManager.Post("Copying data from source to template...", MessageType.InProgress);
                    if (sourceRowCount >= startRow && sourceColCount >= startCol)
                    {
                        // Determine the actual start row for data, assuming row 1 is a header.
                        int sourceDataActualStartRow = (startRow == 1 && sourceRowCount > 1) ? 2 : startRow;

                        if (sourceRowCount >= sourceDataActualStartRow)
                        {
                            ExcelRange sourceRangeToCopy = sourceWorksheet.Cells[sourceDataActualStartRow, startCol, sourceRowCount, sourceColCount];
                            ExcelRange destStartCellForData = destinationDataWorksheet.Cells[2, 1];
                            sourceRangeToCopy.Copy(destStartCellForData);
                            Logger.LogInfo($"Data copied from '{sourceSheetName}' to '{destinationDataSheetName}'.");
                        }
                    }
                    _statusManager.Post("Initial data copy to 'DATA' sheet complete.", MessageType.InProgress);
                    cancellationToken.ThrowIfCancellationRequested();

                    // Apply specific filtering for the 'Daily (5days >= £1000)' report type.
                    if (reportType == ReportType.Daily5Day1k)
                    {
                        decimal filterThreshold = _configuration.GetValue<decimal>("OperationalParameters:Daily5Day1kFilteringThreshold", 1000m);
                        _statusManager.Post($"Filtering for values >= £{filterThreshold:N0}...", MessageType.InProgress);
                        await FilterDataSheetAsync(destinationDataWorksheet, dataColumnMap["Price"], filterThreshold, cancellationToken);
                    }

                    // ADDED: New filtering logic for the NewCustomer report type.
                    else if (reportType == ReportType.NewCustomer)
                    {
                        _statusManager.Post("Filtering for New Customers by Posting Code...", MessageType.InProgress);
                        var postingCodes = _configuration.GetSection(AppConfigKeys.OperationalParameters.NewCustomerPostingCodes).Get<List<string>>();
                        if (postingCodes == null || !postingCodes.Any())
                        {
                            throw new InvalidOperationException("New Customer posting codes are not configured in appsettings.json.");
                        }
                        await FilterDataSheetByPostingCodeAsync(destinationDataWorksheet, dataColumnMap["Posting Code"], new HashSet<string>(postingCodes, StringComparer.OrdinalIgnoreCase), cancellationToken);
                        destinationDataWorksheet = destinationPackage.Workbook.Worksheets[destinationDataSheetName];
                    }
                    _statusManager.Post("Data preparation in 'DATA' sheet complete.", MessageType.InProgress);

                    // Perform all post-copy operations like populating the 'Analysis' sheet.
                    await ProcessPostCopyOperationsAsync(destinationPackage, destinationDataWorksheet, analysisSheet, dataColumnMap, analysisColumnMap, reportType, selectedFinYear, sourceFilePath, reportDate, cancellationToken);

                    // If requested, create the 'Lead Time Analysis' sheet.
                    bool shouldIncludeLeadTimeSheet = (manualParams?.IncludeLeadTimeAnalysis ?? autoRunDef?.IncludeLeadTimeAnalysis) ?? false;
                    if (shouldIncludeLeadTimeSheet)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        await CreateLeadTimeAnalysisSheetAsync(destinationPackage, destinationDataSheetName, cancellationToken);
                    }

                    // Save all changes to the temporary Excel file.
                    _statusManager.Post("Saving processed file...", MessageType.InProgress);
                    await destinationPackage.SaveAsync(cancellationToken);
                }

                // Finalise the file by renaming the temporary file to its final name.
                _statusManager.Post("Finalising file...", MessageType.InProgress);
                string generatedFileName = await Task.Run(() => GenerateFinalFileName(reportType, reportDate, DateTime.Now), cancellationToken);
                finalFilePath = Path.Combine(fullOutputFolderPath, generatedFileName);
                await RenameFileWithRetryAsync(tempFilePath, finalFilePath, cancellationToken);
                tempFilePath = null; // Mark temp file as handled to prevent deletion in the finally block.

                // Report completion.
                _statusManager.Post("Excel processing complete.", MessageType.Success);
                stopwatch.Stop();
                Logger.LogInfo($"Excel processing finished. Final file: {finalFilePath}. Duration: {stopwatch.ElapsedMilliseconds}ms.");
                return finalFilePath;
            }
            catch (OperationCanceledException)
            {
                // Handle cancellation gracefully.
                stopwatch.Stop();
                Logger.LogWarning($"Excel processing was cancelled. Duration: {stopwatch.ElapsedMilliseconds}ms.");
                _statusManager.Post("Operation cancelled.", MessageType.Warning);
                return null;
            }
            catch (Exception ex)
            {
                // Handle any other exceptions, log them, and report the error to the user.
                stopwatch.Stop();
                Logger.LogError($"Unexpected error during Excel processing: {ex.Message}. Duration: {stopwatch.ElapsedMilliseconds}ms.", ex);
                _statusManager.Post($"Error: {ex.Message.Split('\n').FirstOrDefault()}", MessageType.Error);
                return null;
            }
            finally
            {
                // Ensure the temporary file is cleaned up if an error occurred before it was renamed.
                if (tempFilePath != null && File.Exists(tempFilePath))
                {
                    try
                    {
                        File.Delete(tempFilePath);
                        Logger.LogInfo($"Deleted lingering temporary file: {tempFilePath}");
                    }
                    catch (Exception cleanupEx)
                    {
                        Logger.LogWarning($"Failed to delete temporary file '{tempFilePath}' during cleanup: {cleanupEx.Message}");
                    }
                }
            }
        }

        /// <summary>
        /// Gets the current financial year string (e.g., "2023_24" or "FY 23/24").
        /// Uses configured financial year start month and day.
        /// </summary>
        /// <param name="useUnderscoreFormat">If true, returns format "YYYY_YY" (e.g., "2023_24"). Otherwise, "FY YY/YY" (e.g., "FY 23/24").</param>
        /// <returns>The formatted financial year string.</returns>
        public string GetCurrentFinancialYear(bool useUnderscoreFormat = false)
        {
            Logger.LogTrace($"Entering GetCurrentFinancialYear(useUnderscoreFormat: {useUnderscoreFormat})");
            DateTime today = DateTime.Today;
            // Read financial year start month/day from configuration.
            int finYearStartMonth = _configuration.GetValue<int>("OperationalParameters:FinancialYearStartMonth", 5); // Default May
            int finYearStartDay = _configuration.GetValue<int>("OperationalParameters:FinancialYearStartDay", 1);   // Default 1st

            // Determine the calendar year in which the current financial year started.
            int startYear = (today.Month > finYearStartMonth || (today.Month == finYearStartMonth && today.Day >= finYearStartDay))
                            ? today.Year
                            : today.Year - 1;
            int endYear = startYear + 1;

            string result = useUnderscoreFormat
                ? $"{startYear}_{endYear.ToString()[2..]}" // Format: 2023_24
                : $"FY {startYear.ToString()[2..]}/{endYear.ToString()[2..]}"; // Format: FY 23/24

            Logger.LogTrace($"Exiting GetCurrentFinancialYear. Result: {result}");
            return result;
        }

        /// <summary>
        /// Gets the previous financial year string from a given current financial year string (underscore format).
        /// </summary>
        /// <param name="currentFinancialYearUnderscore">The current financial year in "YYYY_YY" format (e.g., "2023_24").</param>
        /// <returns>The previous financial year in "YYYY_YY" format, or null if input is invalid.</returns>
        public string? GetPreviousFinancialYear(string currentFinancialYearUnderscore)
        {
            if (string.IsNullOrEmpty(currentFinancialYearUnderscore))
            {
                return null;
            }
            string[] parts = currentFinancialYearUnderscore.Split('_');
            if (parts.Length == 2 && int.TryParse(parts[0], out int startYear))
            {
                int prevStartYear = startYear - 1;
                return $"{prevStartYear}_{startYear.ToString()[2..]}";
            }
            return null;
        }

        /// <summary>
        /// Validates if a given date range falls entirely within a specified financial year (underscore format).
        /// </summary>
        /// <param name="selectedFinYearUnderscore">The financial year to validate against, in "YYYY_YY" format (e.g., "2023_24").</param>
        /// <param name="fromDate">The start date of the range to check.</param>
        /// <param name="toDate">The end date of the range to check.</param>
        /// <returns>True if the date range is valid for the financial year; otherwise, false.</returns>
        public bool IsFinancialYearValid(string selectedFinYearUnderscore, DateTime fromDate, DateTime toDate)
        {
            if (string.IsNullOrEmpty(selectedFinYearUnderscore))
            {
                return false;
            }
            string[] parts = selectedFinYearUnderscore.Split('_');
            if (parts.Length == 2 && int.TryParse(parts[0], out int startYear))
            {
                int finYearStartMonth = _configuration.GetValue<int>("OperationalParameters:FinancialYearStartMonth", 5);
                int finYearStartDay = _configuration.GetValue<int>("OperationalParameters:FinancialYearStartDay", 1);

                DateTime fyStartDate = new DateTime(startYear, finYearStartMonth, finYearStartDay);
                DateTime fyEndDate = fyStartDate.AddYears(1).AddDays(-1);

                return fromDate >= fyStartDate && toDate <= fyEndDate;
            }
            return false;
        }

        /// <summary>
        /// Gets the expected full file path for a final processed report.
        /// Used for checking if a report for the period already exists.
        /// </summary>
        /// <param name="reportType">The type of the report.</param>
        /// <param name="baseFileSaveLocation">The base directory where final reports are saved.</param>
        /// <param name="reportDate">The primary date for the report (e.g., end date).</param>
        /// <returns>The expected full file path, or null if an error occurs.</returns>
        public string? GetExpectedFinalFilePath(ReportType reportType, string baseFileSaveLocation, DateTime reportDate)
        {
            try
            {
                if (reportDate == default && reportType != ReportType.Custom)
                {
                    reportDate = DateTime.Today;
                }

                DateTime folderTimestampDate = reportType == ReportType.Custom ? DateTime.Now : reportDate;
                string? folderPath = FolderCreation.GetReportSpecificFolderPath(reportType, baseFileSaveLocation, folderTimestampDate, _configuration);
                if (!string.IsNullOrEmpty(folderPath))
                {
                    string fileName = GenerateFinalFileName(reportType, reportDate, DateTime.Now);
                    return Path.Combine(folderPath, fileName);
                }
            }
            catch (Exception ex)
            {
                Logger.LogError($"Error in GetExpectedFinalFilePath: {ex.Message}", ex);
            }
            return null;
        }

        #endregion

        #region Private Processing Steps

        /// <summary>
        /// Orchestrates the sequence of operations that occur after the initial raw data has been copied
        /// to the template's 'DATA' sheet. This includes populating the 'Analysis' sheet, running calculations,
        /// cleaning up unused rows, and appending data to the central Power BI file if required.
        /// </summary>
        private async Task ProcessPostCopyOperationsAsync(
            ExcelPackage package,
            ExcelWorksheet sourceDataWorksheet,
            ExcelWorksheet targetAnalysisWorksheet,
            Dictionary<string, int> dataColumnMap,
            Dictionary<string, int> analysisColumnMap,
            ReportType reportType,
            string selectedFinYear,
            string originalSourceFilePath,
            DateTime reportDate,
            CancellationToken cancellationToken)
        {
            // Log the start of the post-copy process.
            Logger.LogTrace($"Entering ProcessPostCopyOperationsAsync for report type: {reportType}");
            var stopwatch = Stopwatch.StartNew();

            // Retrieve additional sheet and pivot table names from configuration.
            string powerBiSheetName = _configuration.GetValue<string>("OperationalParameters:ExcelSheetNames:PowerBiDataSheet", "powerBI")!;
            string monthlyOrderPivotSheetName = _configuration.GetValue<string>("OperationalParameters:ExcelSheetNames:MonthlyOrderPivotSheet", "OrderPivot")!;
            string monthlyEstimatePivotSheetName = _configuration.GetValue<string>("OperationalParameters:ExcelSheetNames:MonthlyEstimatePivotSheet", "Estimate Success PivotTable")!;
            string monthlyOrderPivotName = _configuration.GetValue<string>("OperationalParameters:PivotTableNames:MonthlyOrderPivot", "PivotTable1")!;
            string monthlyEstimatePivotName = _configuration.GetValue<string>("OperationalParameters:PivotTableNames:MonthlyEstimatePivot", "PivotTable3")!;

            // 1. Extract unique customers from the 'DATA' sheet and populate them into the 'Analysis' sheet.
            _statusManager.Post("Extracting unique customers to Analysis sheet...", MessageType.InProgress);
            await ExtractUniqueCustomersAsync(sourceDataWorksheet, targetAnalysisWorksheet, dataColumnMap, analysisColumnMap, reportType, originalSourceFilePath, reportDate, cancellationToken);
            cancellationToken.ThrowIfCancellationRequested();

            // 2. Trigger the calculation of all formulas in the workbook.
            _statusManager.Post("Calculating formulas in Analysis sheet...", MessageType.InProgress);
            await Task.Run(() => CalculateSheet(package, targetAnalysisWorksheet.Name), cancellationToken);
            cancellationToken.ThrowIfCancellationRequested();

            // 3. For specific report types, filter the 'Analysis' sheet to remove irrelevant rows.
            if (reportType == ReportType.Daily5Day1k)
            {
                _statusManager.Post("Filtering Analysis sheet for zero estimates...", MessageType.InProgress);
                await FilterAnalysisSheetForZeroEstimatesAsync(targetAnalysisWorksheet, analysisColumnMap, cancellationToken);
                cancellationToken.ThrowIfCancellationRequested();
            }

            // 4. Clean up any unused template rows below the last populated customer in the 'Analysis' sheet.
            _statusManager.Post("Cleaning unused rows...", MessageType.InProgress);
            await Task.Run(() => ClearContentBelowLastCustomer(targetAnalysisWorksheet, analysisColumnMap), cancellationToken);
            cancellationToken.ThrowIfCancellationRequested();

            // 5. For reports that use templates with pivot tables, set them to refresh when the file is opened.
            if (reportType is ReportType.Monthly or ReportType.Quarterly or ReportType.Annual or ReportType.Custom)
            {
                _statusManager.Post("Setting pivot tables to refresh...", MessageType.InProgress);
                await Task.Run(() => RefreshPivotTable(package, monthlyOrderPivotSheetName, monthlyOrderPivotName), cancellationToken);
                await Task.Run(() => RefreshPivotTable(package, monthlyEstimatePivotSheetName, monthlyEstimatePivotName), cancellationToken);
                cancellationToken.ThrowIfCancellationRequested();
            }

            // 6. For Weekly reports, append the processed data to the central Power BI source file.
            if (reportType == ReportType.Weekly)
            {
                _statusManager.Post("Appending data to Power BI source file...", MessageType.InProgress);
                await CopyAnalysisDataToPowerBIReportAsync(package, targetAnalysisWorksheet.Name, powerBiSheetName, reportType, originalSourceFilePath, reportDate, cancellationToken);
                cancellationToken.ThrowIfCancellationRequested();
            }

            // Log the completion of the post-copy process.
            stopwatch.Stop();
            Logger.LogDebug($"Exiting ProcessPostCopyOperationsAsync. Duration: {stopwatch.ElapsedMilliseconds}ms");
        }

        #endregion

        #region Private Helper Methods

        /// <summary>
        /// Scans the header row of a worksheet to build a dictionary that maps column names to their 1-based index.
        /// This makes the application resilient to changes in column order within the template files.
        /// </summary>
        /// <param name="worksheet">The worksheet to scan.</param>
        /// <param name="headerRow">The row number where the headers are located.</param>
        /// <param name="requiredColumns">An enumerable of column names that must be present in the header.</param>
        /// <returns>A dictionary mapping each column name to its integer index.</returns>
        /// <exception cref="InvalidOperationException">
        /// Thrown if the header row does not exist or if a required column is not found.
        /// </exception>
        private Dictionary<string, int> MapColumnIndices(ExcelWorksheet worksheet, int headerRow, IEnumerable<string> requiredColumns)
        {
            // Initialise a case-insensitive dictionary to store the mapping.
            var columnMap = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);

            // Check if the worksheet dimensions are valid and the header row exists.
            if (worksheet.Dimension == null || worksheet.Dimension.End.Row < headerRow)
            {
                throw new InvalidOperationException($"Header row {headerRow} does not exist in worksheet '{worksheet.Name}'. The sheet is empty or malformed.");
            }

            // Iterate through each column in the header row.
            for (int col = 1; col <= worksheet.Dimension.End.Column; col++)
            {
                // Get the trimmed header text from the cell.
                var cellValue = worksheet.Cells[headerRow, col].Value?.ToString()?.Trim();

                // If the header text is not empty and not already in the map, add it.
                if (!string.IsNullOrEmpty(cellValue) && !columnMap.ContainsKey(cellValue))
                {
                    columnMap[cellValue] = col;
                }
            }

            // Verify that all required columns were found in the map.
            foreach (var requiredColumn in requiredColumns)
            {
                if (!columnMap.ContainsKey(requiredColumn))
                {
                    // If a required column is missing, throw a descriptive exception.
                    throw new InvalidOperationException($"Required column '{requiredColumn}' not found in the header of worksheet '{worksheet.Name}'. Please check the template file.");
                }
            }

            // Return the completed map.
            return columnMap;
        }

        /// <summary>
        /// Ensures the destination 'DATA' sheet exists in the workbook. If it exists, it clears any old data.
        /// If it does not exist, it creates the sheet and copies the header row from the source worksheet.
        /// </summary>
        /// <param name="package">The Excel package to modify.</param>
        /// <param name="sheetName">The name of the destination sheet (e.g., "DATA").</param>
        /// <param name="sourceWorksheet">The source worksheet to copy headers from if the destination sheet needs to be created.</param>
        /// <returns>The prepared destination worksheet.</returns>
        private ExcelWorksheet GetOrCreateDestinationWorksheet(ExcelPackage package, string sheetName, ExcelWorksheet sourceWorksheet)
        {
            // Attempt to get the worksheet by name.
            ExcelWorksheet? worksheet = package.Workbook.Worksheets[sheetName];

            // If the sheet does not exist...
            if (worksheet == null)
            {
                // ...create it.
                worksheet = package.Workbook.Worksheets.Add(sheetName);
                Logger.LogInfo($"Created destination sheet '{sheetName}'.");

                // Copy the header row from the source worksheet.
                CopyHeaders(sourceWorksheet, worksheet);
            }
            else // If the sheet already exists...
            {
                // ...clear any data from previous runs, preserving the header row.
                if (worksheet.Dimension != null && worksheet.Dimension.Rows > 1)
                {
                    worksheet.DeleteRow(2, worksheet.Dimension.Rows - 1);
                }
            }
            return worksheet;
        }

        /// <summary>
        /// Extracts unique customer names + posting code pairs from the 'DATA' sheet and populates them into the 'Analysis' sheet.
        /// It also populates related metadata columns like the report date, source file name, and inserts the formula for Contract Status.
        /// </summary>
        private async Task ExtractUniqueCustomersAsync(
            ExcelWorksheet dataSheet,
            ExcelWorksheet analysisSheet,
            Dictionary<string, int> dataColumnMap,
            Dictionary<string, int> analysisColumnMap,
            ReportType reportType,
            string originalSourceFilePath,
            DateTime reportDate,
            CancellationToken cancellationToken)
        {
            // --- 1. Get Column Indices from Maps ---
            // Data sheet columns
            int customerColData = dataColumnMap["Customer"];
            int postingCodeColData = dataColumnMap["Posting Code"];
            int repColData = dataColumnMap["Rep"];
            int orderedColData = dataColumnMap["Ordered"];
            int priceColData = dataColumnMap["Price"];

            // Analysis sheet columns
            int customerColAnalysis = analysisColumnMap["Customer"];
            int postingCodeColAnalysis = analysisColumnMap["Posting Code"];
            // MODIFIED: This column index is now used for placing a formula, not data.
            int contractStatusColAnalysis = analysisColumnMap["Contract Status"];
            int repColAnalysis = analysisColumnMap["Rep"];
            int numEstimatesColAnalysis = analysisColumnMap["Number of Estimates"];
            int estimatesWonColAnalysis = analysisColumnMap["Estimates Won"];
            int estimatesNotWonColAnalysis = analysisColumnMap["Estimates Not Won"];
            int winPercentColAnalysis = analysisColumnMap["% Win"];
            int valueOfEstimatesColAnalysis = analysisColumnMap["Value of Estimates"];
            int valueWonColAnalysis = analysisColumnMap["Value of Estimates Won"];
            int valueNotConfirmedColAnalysis = analysisColumnMap["Value of Est Not Confirmed"];
            int valueWonPercentColAnalysis = analysisColumnMap["Value Won %"];
            int sourceFileColAnalysis = analysisColumnMap["SOURCE FILE"];
            int dateColAnalysis = analysisColumnMap["CONVERTED DATE"];
            int finYearColAnalysis = analysisColumnMap["FY"];

            // --- 2. Define Sheet Structure ---
            const int analysisStartRow = 6;
            int dataSheetRowCount = dataSheet.Dimension?.Rows ?? 0;
            const int dataRangeSize = 50000;

            // --- 3. Prepare Metadata ---
            string sourceFileNameForAnalysis = Path.GetFileName(originalSourceFilePath);
            string currentFY = GetCurrentFinancialYear(false);

            // --- 4. Extract Unique Pairs and their Metadata (Rep) ---
            // MODIFIED: The tuple no longer includes ContractStatus as it's not read from the data sheet.
            List<(string CustomerName, string PostingCode, string Rep)> uniqueCustomerData = await Task.Run(() =>
            {
                // The dictionary now only stores the Rep metadata.
                var customerDataDict = new Dictionary<(string, string), string>();
                if (dataSheetRowCount >= 2)
                {
                    for (int row = 2; row <= dataSheetRowCount; row++)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        string? customerName = dataSheet.Cells[row, customerColData].Value?.ToString()?.Trim();
                        string? postingCode = dataSheet.Cells[row, postingCodeColData].Value?.ToString()?.Trim();

                        if (!string.IsNullOrWhiteSpace(customerName) && !string.IsNullOrWhiteSpace(postingCode))
                        {
                            var key = (customerName, postingCode);
                            if (!customerDataDict.ContainsKey(key))
                            {
                                string rep = dataSheet.Cells[row, repColData].Value?.ToString()?.Trim() ?? "Not Found";
                                // MODIFIED: No longer reading Contract Status here.
                                customerDataDict.Add(key, rep);
                            }
                        }
                    }
                }
                // MODIFIED: Select statement updated for the new tuple structure.
                return customerDataDict.Select(kvp => (kvp.Key.Item1, kvp.Key.Item2, kvp.Value))
                                     .OrderBy(d => d.Item1).ThenBy(d => d.Item2).ToList();
            }, cancellationToken);

            Logger.LogInfo($"Found {uniqueCustomerData.Count} unique customer/posting code pairs.");

            // --- 5. Pre-clear Analysis Sheet ---
            if (analysisSheet.Dimension != null && analysisSheet.Dimension.Rows >= analysisStartRow)
            {
                analysisSheet.Cells[analysisStartRow, 1, analysisSheet.Dimension.End.Row, analysisSheet.Dimension.End.Column].Clear();
            }

            // --- 6. Populate Analysis Sheet with Data, Formulas, and Formatting ---
            for (int i = 0; i < uniqueCustomerData.Count; i++)
            {
                cancellationToken.ThrowIfCancellationRequested();
                // MODIFIED: Deconstructed the updated tuple without ContractStatus.
                var (customerName, postingCode, rep) = uniqueCustomerData[i];
                int targetRow = analysisStartRow + i;

                // Populate the keys and metadata
                analysisSheet.Cells[targetRow, customerColAnalysis].Value = customerName;
                analysisSheet.Cells[targetRow, postingCodeColAnalysis].Value = postingCode;
                analysisSheet.Cells[targetRow, repColAnalysis].Value = rep;
                analysisSheet.Cells[targetRow, dateColAnalysis].Value = reportDate.Date;
                analysisSheet.Cells[targetRow, finYearColAnalysis].Value = currentFY;
                analysisSheet.Cells[targetRow, sourceFileColAnalysis].Value = sourceFileNameForAnalysis;

                // --- Build and Write Formulas ---
                string customerAddress = $"Analysis!{ExcelCellAddress.GetColumnLetter(customerColAnalysis)}{targetRow}";
                string postingCodeAddress = $"Analysis!{ExcelCellAddress.GetColumnLetter(postingCodeColAnalysis)}{targetRow}";

                // MODIFIED: Insert the formula for Contract Status instead of a static value.
                string contractStatusFormula = $"IF(ISNUMBER(SEARCH(\"NON-CONTRACT\",{customerAddress})),\"NON-CONTRACT\",\"CONTRACT\")";
                analysisSheet.Cells[targetRow, contractStatusColAnalysis].Formula = contractStatusFormula;

                // --- Build and Write the two-criteria formulas for other columns ---
                string customerCritRange = $"DATA!${ExcelCellAddress.GetColumnLetter(customerColData)}$2:${ExcelCellAddress.GetColumnLetter(customerColData)}${dataRangeSize}";
                string postingCodeCritRange = $"DATA!${ExcelCellAddress.GetColumnLetter(postingCodeColData)}$2:${ExcelCellAddress.GetColumnLetter(postingCodeColData)}${dataRangeSize}";
                string orderedCritRange = $"DATA!${ExcelCellAddress.GetColumnLetter(orderedColData)}$2:${ExcelCellAddress.GetColumnLetter(orderedColData)}${dataRangeSize}";
                string priceSumRange = $"DATA!${ExcelCellAddress.GetColumnLetter(priceColData)}$2:${ExcelCellAddress.GetColumnLetter(priceColData)}${dataRangeSize}";

                analysisSheet.Cells[targetRow, numEstimatesColAnalysis].Formula = $"COUNTIFS({customerCritRange},{customerAddress},{postingCodeCritRange},{postingCodeAddress},{orderedCritRange},\"<>Superseded\")";
                analysisSheet.Cells[targetRow, estimatesWonColAnalysis].Formula = $"COUNTIFS({customerCritRange},{customerAddress},{postingCodeCritRange},{postingCodeAddress},{orderedCritRange},\"Yes\")";
                analysisSheet.Cells[targetRow, estimatesNotWonColAnalysis].Formula = $"COUNTIFS({customerCritRange},{customerAddress},{postingCodeCritRange},{postingCodeAddress},{orderedCritRange},\"No\")";
                analysisSheet.Cells[targetRow, winPercentColAnalysis].Formula = $"IF({ExcelCellAddress.GetColumnLetter(numEstimatesColAnalysis)}{targetRow}>0,{ExcelCellAddress.GetColumnLetter(estimatesWonColAnalysis)}{targetRow}/{ExcelCellAddress.GetColumnLetter(numEstimatesColAnalysis)}{targetRow},0)";

                analysisSheet.Cells[targetRow, valueOfEstimatesColAnalysis].Formula = $"SUMIFS({priceSumRange},{customerCritRange},{customerAddress},{postingCodeCritRange},{postingCodeAddress},{orderedCritRange},\"<>Superseded\")";
                analysisSheet.Cells[targetRow, valueWonColAnalysis].Formula = $"SUMIFS({priceSumRange},{customerCritRange},{customerAddress},{postingCodeCritRange},{postingCodeAddress},{orderedCritRange},\"Yes\")";
                analysisSheet.Cells[targetRow, valueNotConfirmedColAnalysis].Formula = $"SUMIFS({priceSumRange},{customerCritRange},{customerAddress},{postingCodeCritRange},{postingCodeAddress},{orderedCritRange},\"No\")";
                analysisSheet.Cells[targetRow, valueWonPercentColAnalysis].Formula = $"IF({ExcelCellAddress.GetColumnLetter(valueOfEstimatesColAnalysis)}{targetRow}>0,{ExcelCellAddress.GetColumnLetter(valueWonColAnalysis)}{targetRow}/{ExcelCellAddress.GetColumnLetter(valueOfEstimatesColAnalysis)}{targetRow},0)";
            }

            // --- 7. Apply Number Formatting to Columns ---
            if (uniqueCustomerData.Any())
            {
                int endRow = analysisStartRow + uniqueCustomerData.Count - 1;

                //format the date
                analysisSheet.Cells[analysisStartRow, dateColAnalysis, endRow, dateColAnalysis].Style.Numberformat.Format = "dd/MM/yyyy";

                // Currency Format
                analysisSheet.Cells[analysisStartRow, valueOfEstimatesColAnalysis, endRow, valueNotConfirmedColAnalysis].Style.Numberformat.Format = "£#,##0.00";
                // Percentage Format
                analysisSheet.Cells[analysisStartRow, winPercentColAnalysis, endRow, winPercentColAnalysis].Style.Numberformat.Format = "0%";
                analysisSheet.Cells[analysisStartRow, valueWonPercentColAnalysis, endRow, valueWonPercentColAnalysis].Style.Numberformat.Format = "0%";
            }
        }

        /// <summary>
        /// Triggers the calculation of all formulas in the workbook. Note that EPPlus has limitations,
        /// and complex formulas may still require a manual refresh in Excel.
        /// </summary>
        /// <param name="package">The Excel package to calculate.</param>
        /// <param name="sheetName">The name of the primary sheet being processed, for logging purposes.</param>
        private void CalculateSheet(ExcelPackage package, string sheetName)
        {
            // Get the worksheet from the package.
            ExcelWorksheet? worksheet = package.Workbook.Worksheets[sheetName];
            if (worksheet != null)
            {
                try
                {
                    // Trigger calculation for the entire workbook.
                    package.Workbook.Calculate();
                    Logger.LogInfo($"Workbook calculation triggered for sheet '{sheetName}'.");
                }
                catch (Exception ex)
                {
                    // Log a warning if calculation fails.
                    Logger.LogWarning($"Error during Excel workbook calculation for sheet '{sheetName}': {ex.Message}. Manual refresh may be needed.", ex);
                }
            }
        }

        /// <summary>
        /// Clears content from rows in the 'Analysis' sheet that are below the last row containing a customer name.
        /// This is used to clean up unused rows from the template.
        /// </summary>
        /// <param name="worksheet">The 'Analysis' worksheet to clean.</param>
        /// <param name="analysisColumnMap">The column map for the 'Analysis' sheet.</param>
        private void ClearContentBelowLastCustomer(ExcelWorksheet worksheet, Dictionary<string, int> analysisColumnMap)
        {
            // Check if the worksheet has any data.
            if (worksheet.Dimension == null) return;

            // Get the column index for the customer name.
            int customerNameColIdx = analysisColumnMap["Customer"];
            int firstColToClear = 1;
            int lastColToClear = worksheet.Dimension.End.Column;

            // Define where customer data starts.
            const int customerDataStartRow = 6;
            int lastActualDataRow = customerDataStartRow - 1;

            // Find the last row that contains a customer name.
            for (int r = worksheet.Dimension.End.Row; r >= customerDataStartRow; r--)
            {
                if (worksheet.Cells[r, customerNameColIdx].Value != null && !string.IsNullOrWhiteSpace(worksheet.Cells[r, customerNameColIdx].Value.ToString()))
                {
                    lastActualDataRow = r;
                    break;
                }
            }

            // Determine the starting row for clearing content.
            int startClearTargetRow = Math.Max(lastActualDataRow + 1, customerDataStartRow);

            // If there are rows to clear, clear them.
            if (startClearTargetRow <= worksheet.Dimension.End.Row)
            {
                worksheet.Cells[startClearTargetRow, firstColToClear, worksheet.Dimension.End.Row, lastColToClear].Clear();
            }
        }

        /// <summary>
        /// Sets the specified pivot table to refresh its data when the Excel file is opened.
        /// </summary>
        /// <param name="package">The Excel package containing the pivot table.</param>
        /// <param name="sheetName">The name of the sheet containing the pivot table.</param>
        /// <param name="pivotTableName">The name of the pivot table to refresh.</param>
        private void RefreshPivotTable(ExcelPackage package, string sheetName, string pivotTableName)
        {
            // Get the worksheet.
            ExcelWorksheet? worksheet = package.Workbook.Worksheets[sheetName];
            if (worksheet == null) return;

            // Find the pivot table by name.
            ExcelPivotTable? pivotTable = worksheet.PivotTables.FirstOrDefault(pt => pt.Name.Equals(pivotTableName, StringComparison.OrdinalIgnoreCase));
            if (pivotTable != null)
            {
                try
                {
                    // Set the pivot table to refresh its cache.
                    pivotTable.CacheDefinition.Refresh();
                }
                catch (Exception ex)
                {
                    // Log any errors.
                    Logger.LogError($"Error refreshing pivot table '{pivotTableName}' in '{sheetName}': {ex.Message}", ex);
                }
            }
        }

        /// <summary>
        /// Filters rows in the specified worksheet based on a numeric threshold in a given column.
        /// Rows where the value is less than the threshold, or cannot be parsed as a decimal, are deleted.
        /// </summary>
        /// <param name="worksheet">The Excel worksheet to filter.</param>
        /// <param name="priceColumnIndex">The 1-based index of the column containing numeric values to check.</param>
        /// <param name="threshold">The decimal threshold. Rows with values less than this will be removed.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        private async Task FilterDataSheetAsync(ExcelWorksheet worksheet, int priceColumnIndex, decimal threshold, CancellationToken cancellationToken)
        {
            if (worksheet.Dimension == null || worksheet.Dimension.Rows < 2) return;

            await Task.Run(() =>
            {
                int initialRowCount = worksheet.Dimension.Rows;
                for (int r = initialRowCount; r >= 2; r--)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var cellValue = worksheet.Cells[r, priceColumnIndex].Value;
                    bool deleteRow = true;

                    if (cellValue != null)
                    {
                        string valStr = cellValue.ToString()!.Replace("£", "").Replace(",", "").Trim();
                        if (decimal.TryParse(valStr, NumberStyles.Any, CultureInfo.InvariantCulture, out decimal amount))
                        {
                            if (amount >= threshold)
                            {
                                deleteRow = false;
                            }
                        }
                    }

                    if (deleteRow)
                    {
                        worksheet.DeleteRow(r, 1);
                    }
                }
            }, cancellationToken);
        }
        /// <summary>
        /// Filters rows in the 'DATA' worksheet based on a list of valid Posting Codes.
        /// This method has been optimized to copy wanted rows to a new sheet instead of deleting unwanted rows.
        /// </summary>
        /// <param name="worksheet">The 'DATA' worksheet to filter.</param>
        /// <param name="postingCodeColumnIndex">The 1-based index of the 'Posting Code' column.</param>
        /// <param name="validPostingCodes">A HashSet containing the list of valid posting codes for efficient lookup.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
        private async Task FilterDataSheetByPostingCodeAsync(ExcelWorksheet worksheet, int postingCodeColumnIndex, HashSet<string> validPostingCodes, CancellationToken cancellationToken)
        {
            if (worksheet.Dimension == null || worksheet.Dimension.Rows < 2) return;

            await Task.Run(() =>
            {
                // 1. Create a new temporary worksheet.
                var workbook = worksheet.Workbook;
                string originalSheetName = worksheet.Name;
                string tempSheetName = $"_temp_{originalSheetName}_{Guid.NewGuid()}";
                var tempWorksheet = workbook.Worksheets.Add(tempSheetName);

                // 2. Copy the header row from the original sheet to the temporary one.
                worksheet.Cells[1, 1, 1, worksheet.Dimension.End.Column].Copy(tempWorksheet.Cells[1, 1]);
                int destRow = 2; // Initialize the destination row counter for the temp sheet.

                // 3. Iterate through the original sheet and copy only the rows we want to keep.
                for (int r = 2; r <= worksheet.Dimension.End.Row; r++)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var cellValue = worksheet.Cells[r, postingCodeColumnIndex].Value?.ToString()?.Trim();

                    // Check if the cell value is in our list of valid codes.
                    if (!string.IsNullOrEmpty(cellValue) && validPostingCodes.Contains(cellValue))
                    {
                        // If it is, copy the entire row to the temporary sheet.
                        worksheet.Cells[r, 1, r, worksheet.Dimension.End.Column].Copy(tempWorksheet.Cells[destRow, 1]);
                        destRow++;
                    }
                }

                // 4. Replace the original sheet with the newly created, filtered sheet.
                int originalIndex = worksheet.Index;
                workbook.Worksheets.Delete(worksheet);
                tempWorksheet.Name = originalSheetName;
                // CORRECTED LINE: Use the MoveBefore method to correctly position the worksheet.
                if (originalIndex <= workbook.Worksheets.Count)
                {
                    // Get the sheet currently at the target position to move our new sheet before it.
                    var sheetToMoveBefore = workbook.Worksheets[originalIndex];
                    workbook.Worksheets.MoveBefore(tempWorksheet.Name, sheetToMoveBefore.Name);
                }
                // If the original sheet was the last one, the new sheet is already in the correct final position.

            }, cancellationToken);
        }

        /// <summary>
        /// Filters the "Analysis" sheet to remove rows where the "No of Estimates" is zero or empty.
        /// </summary>
        /// <param name="worksheet">The "Analysis" worksheet.</param>
        /// <param name="analysisColumnMap">The column map for the 'Analysis' sheet.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        private async Task FilterAnalysisSheetForZeroEstimatesAsync(ExcelWorksheet worksheet, Dictionary<string, int> analysisColumnMap, CancellationToken cancellationToken)
        {
            if (worksheet.Dimension == null) return;

            int customerCol = analysisColumnMap["Customer"];
            int estimatesCol = analysisColumnMap["Number of Estimates"];

            await Task.Run(() =>
            {
                const int customerDataStartRow = 6;
                if (worksheet.Dimension.Rows < customerDataStartRow) return;

                int initialRowCount = worksheet.Dimension.Rows;
                for (int r = initialRowCount; r >= customerDataStartRow; r--)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    var customerCell = worksheet.Cells[r, customerCol].Value;
                    if (customerCell == null || string.IsNullOrWhiteSpace(customerCell.ToString()))
                    {
                        continue;
                    }

                    var noOfEstimatesCell = worksheet.Cells[r, estimatesCol].Value;
                    decimal numberOfEstimates = 0;
                    if (noOfEstimatesCell != null)
                    {
                        decimal.TryParse(noOfEstimatesCell.ToString()?.Trim(), NumberStyles.Any, CultureInfo.InvariantCulture, out numberOfEstimates);
                    }

                    if (numberOfEstimates <= 0)
                    {
                        worksheet.DeleteRow(r, 1);
                    }
                }
            }, cancellationToken);
        }

        /// <summary>
        /// Copies header rows from a source worksheet to a destination worksheet.
        /// </summary>
        private void CopyHeaders(ExcelWorksheet sourceSheet, ExcelWorksheet destinationSheet, int startHeaderRow = 1, int endHeaderRow = 1)
        {
            if (sourceSheet.Dimension != null && sourceSheet.Dimension.Rows >= endHeaderRow)
            {
                int actualHeaderColCount = sourceSheet.Dimension.Columns;
                if (actualHeaderColCount > 0)
                {
                    ExcelRange sourceHeaderRange = sourceSheet.Cells[startHeaderRow, 1, endHeaderRow, actualHeaderColCount];
                    ExcelRange destHeaderRange = destinationSheet.Cells[startHeaderRow, 1];
                    sourceHeaderRange.Copy(destHeaderRange);
                }
            }
        }

        /// <summary>
        /// Finds the next available (empty) row in a worksheet.
        /// </summary>
        /// <param name="worksheet">The worksheet to check.</param>
        /// <param name="checkColumn">The 1-based index of the column to check for content.</param>
        /// <returns>The 1-based index of the next free row.</returns>
        private int GetNextFreeRow(ExcelWorksheet worksheet, int checkColumn = 1)
        {
            if (worksheet.Dimension == null) return 1;

            const int firstDataRowAfterHeaders = 2;
            int lastUsedRow = worksheet.Dimension.End.Row;

            if (lastUsedRow < firstDataRowAfterHeaders)
            {
                return firstDataRowAfterHeaders;
            }

            for (int r = lastUsedRow; r >= 1; r--)
            {
                var cell = worksheet.Cells[r, checkColumn].Value;
                if (cell != null && !string.IsNullOrWhiteSpace(cell.ToString()))
                {
                    return Math.Max(r + 1, firstDataRowAfterHeaders);
                }
            }
            return firstDataRowAfterHeaders;
        }

        #endregion

        #region File and Folder Helpers

        /// <summary>
        /// Generates the final filename for a processed report based on its type and date.
        /// </summary>
        /// <param name="reportType">The type of the report.</param>
        /// <param name="reportDate">The primary date for the report.</param>
        /// <param name="runTimestamp">The timestamp of the run, used for uniqueness in custom reports.</param>
        /// <returns>A string representing the generated filename.</returns>
        private string GenerateFinalFileName(ReportType reportType, DateTime reportDate, DateTime runTimestamp)
        {
            // Use a switch expression to determine the filename based on the report type.
            return reportType switch
            {
                ReportType.Daily => $"{reportDate:yyyyMMdd}_Estimate_Success_Rate_Daily.xlsx",
                ReportType.Daily5Day1k => $"{reportDate:yyyyMMdd}_Estimate_Success_Rate_Daily_5day_1k.xlsx",
                ReportType.Weekly => $"{reportDate:yyyyMMdd} Estimate Success Rate.xlsx",
                ReportType.Monthly => $"Estimate Success Rate {reportDate:MMM yy}.xlsx",
                ReportType.Quarterly => $"Estimate Success Rate {ReportHelper.GetQuarterString(reportDate)}.xlsx",
                ReportType.Annual => $"Estimate Success Rate FY {ReportHelper.GetFinancialYearStartCalendarYear(reportDate, _configuration)}-{ReportHelper.GetFinancialYearStartCalendarYear(reportDate, _configuration) + 1}.xlsx",
                ReportType.Custom => $"{reportDate:yyyyMMdd}_{runTimestamp:HHmmss}_Estimate_Success_Rate_Custom.xlsx",
                ReportType.NewCustomer => $"{reportDate:yyyyMMdd}_Estimate_Success_Rate_New_Customer.xlsx", // MODIFIED: Add a filename for the new report
                _ => $"{reportDate:yyyyMMdd}_Estimate_Success_Rate_UnknownType_{runTimestamp:HHmmss}.xlsx",
            };
        }

        /// <summary>
        /// Asynchronously renames or moves a file, with built-in retry logic to handle transient file locks.
        /// </summary>
        /// <param name="sourcePath">The full path to the source file.</param>
        /// <param name="destinationPath">The full path to the destination file.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
        private async Task RenameFileWithRetryAsync(
            string sourcePath,
            string destinationPath,
            CancellationToken cancellationToken)
        {
            // Get retry parameters from configuration.
            int maxRetries = _configuration.GetValue<int>("OperationalParameters:GeneralFileOperationMaxRetries", 5);
            int initialDelayMs = _configuration.GetValue<int>("OperationalParameters:GeneralFileOperationDelayMs", 500);
            int currentDelayMs = initialDelayMs;

            // Loop for the specified number of retries.
            for (int i = 0; i < maxRetries; i++)
            {
                try
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    // Perform the file move operation on a background thread.
                    await Task.Run(() =>
                    {
                        if (File.Exists(destinationPath))
                        {
                            File.Delete(destinationPath);
                        }
                        File.Move(sourcePath, destinationPath);
                    }, cancellationToken);
                    return; // Success, exit the method.
                }
                catch (IOException ex) when (i < maxRetries - 1)
                {
                    // If an IO error occurs and it is not the last attempt, wait and retry.
                    Logger.LogWarning($"Attempt {i + 1}/{maxRetries} failed to move file: {ex.Message}. Retrying in {currentDelayMs}ms...");
                    _statusManager.Post($"Waiting for file access (Attempt {i + 1})...", MessageType.InProgress);
                    await Task.Delay(currentDelayMs, cancellationToken);
                    currentDelayMs *= 2; // Exponential backoff.
                }
                catch (OperationCanceledException)
                {
                    // Re-throw cancellation exceptions immediately.
                    throw;
                }
            }
            // If the loop completes, all retries have failed.
            throw new IOException($"Failed to move file '{sourcePath}' to '{destinationPath}' after {maxRetries} attempts.");
        }

        #endregion

        #region Power BI and File Locking

        /// <summary>
        /// Copies data from the 'Analysis' sheet of the processed report to a central Power BI source Excel file.
        /// This method includes a robust file-locking mechanism to prevent race conditions during concurrent access.
        /// </summary>
        private async Task CopyAnalysisDataToPowerBIReportAsync(
            ExcelPackage sourcePackage,
            string sourceAnalysisSheetName,
            string targetPowerBiSheetName,
            ReportType reportType,
            string originalSourceFilePath,
            DateTime reportDate,
            CancellationToken cancellationToken)
        {
            // Determine the path to the central Power BI file.
            string destinationPowerBiFilePath = GetWeeklyReportPath(Environment.UserName);
            if (string.IsNullOrEmpty(destinationPowerBiFilePath) || !File.Exists(destinationPowerBiFilePath))
            {
                _statusManager.Post("Error: Central Power BI report file not found.", MessageType.Error);
                return;
            }

            // Get the source worksheet.
            ExcelWorksheet? sourceWorksheet = sourcePackage.Workbook.Worksheets[sourceAnalysisSheetName];
            if (sourceWorksheet == null || sourceWorksheet.Dimension == null) return;

            // Define the path for the lock file.
            string lockFilePath = destinationPowerBiFilePath + ".lock";
            FileStream? lockFileStream = null;

            try
            {
                // 1. Acquire a lock on the Power BI file.
                _statusManager.Post("Acquiring lock for Power BI file...", MessageType.InProgress);
                lockFileStream = await AcquireLockFileAsync(lockFilePath, cancellationToken);
                _statusManager.Post("Lock acquired. Processing Power BI file...", MessageType.InProgress);

                // 2. Perform the file modification within the lock.
                using (var destinationPackage = await Task.Run(() => new ExcelPackage(new FileInfo(destinationPowerBiFilePath)), cancellationToken))
                {
                    // Map the columns from the source analysis sheet.
                    var analysisColumnMap = MapColumnIndices(sourceWorksheet, 5, new[] { "Customer", "SOURCE FILE" });
                    int customerCol = analysisColumnMap["Customer"];
                    int sourceFileCol = analysisColumnMap["SOURCE FILE"];

                    // Get or create the destination sheet.
                    ExcelWorksheet? destinationWorksheet = destinationPackage.Workbook.Worksheets[targetPowerBiSheetName];
                    if (destinationWorksheet == null)
                    {
                        destinationWorksheet = destinationPackage.Workbook.Worksheets.Add(targetPowerBiSheetName);
                        CopyHeaders(sourceWorksheet, destinationWorksheet, 1, 5);
                    }

                    // Find the next free row to append data.
                    int nextFreeRowInPowerBiSheet = await Task.Run(() => GetNextFreeRow(destinationWorksheet), cancellationToken);
                    string filenameForPowerBiColumn = GenerateFinalFileName(reportType, reportDate, DateTime.Now);

                    // Copy the data row by row.
                    await Task.Run(() =>
                    {
                        int sourceAnalysisRowCount = sourceWorksheet.Dimension.Rows;
                        int sourceAnalysisColCount = sourceWorksheet.Dimension.End.Column;
                        const int startDataRowInAnalysis = 6;

                        if (sourceAnalysisRowCount >= startDataRowInAnalysis)
                        {
                            for (int sourceRow = startDataRowInAnalysis; sourceRow <= sourceAnalysisRowCount; sourceRow++)
                            {
                                cancellationToken.ThrowIfCancellationRequested();
                                if (sourceWorksheet.Cells[sourceRow, customerCol].Value != null)
                                {
                                    for (int col = 1; col <= sourceAnalysisColCount; col++)
                                    {
                                        destinationWorksheet.Cells[nextFreeRowInPowerBiSheet, col].Value = sourceWorksheet.Cells[sourceRow, col].Value;
                                    }
                                    destinationWorksheet.Cells[nextFreeRowInPowerBiSheet, sourceFileCol].Value = filenameForPowerBiColumn;
                                    nextFreeRowInPowerBiSheet++;
                                }
                            }
                        }
                    }, cancellationToken);

                    // Save the changes to the Power BI file.
                    await destinationPackage.SaveAsync(cancellationToken);
                }
                _statusManager.Post("Data appended to Power BI source.", MessageType.Success);
            }
            catch (OperationCanceledException)
            {
                // Handle cancellation.
                Logger.LogWarning("Operation cancelled while processing Power BI report source.");
                _statusManager.Post("Cancelled update to Power BI source.", MessageType.Warning);
            }
            catch (Exception ex)
            {
                // Handle any other errors.
                Logger.LogError($"Error copying data to Power BI source file: {ex.Message}", ex);
                _statusManager.Post($"Error (Power BI): {ex.Message.Split('\n').FirstOrDefault()}", MessageType.Error);
            }
            finally
            {
                // 3. Release the lock by disposing and deleting the lock file. This is critical.
                if (lockFileStream != null)
                {
                    lockFileStream.Dispose();
                    try
                    {
                        File.Delete(lockFilePath);
                        Logger.LogInfo("Released Power BI file lock.");
                    }
                    catch (Exception ex)
                    {
                        Logger.LogError($"CRITICAL: Failed to delete lock file '{lockFilePath}'. This may require manual intervention.", ex);
                        _statusManager.Post("CRITICAL: Failed to release Power BI file lock!", MessageType.Error);
                    }
                }
            }
        }

        /// <summary>
        /// Asynchronously acquires a lock file for a resource, waiting and retrying if the lock is already held.
        /// This prevents race conditions when accessing shared files.
        /// </summary>
        /// <param name="lockFilePath">The full path of the lock file to create (e.g., "report.xlsx.lock").</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
        /// <returns>A FileStream for the created lock file. The caller must dispose of this stream to release the lock.</returns>
        private async Task<FileStream> AcquireLockFileAsync(string lockFilePath, CancellationToken cancellationToken)
        {
            // Get timeout and retry settings from configuration.
            int timeoutMinutes = _configuration.GetValue<int>("OperationalParameters:FileLockTimeoutMinutes", 2);
            int retryDelayMs = _configuration.GetValue<int>("OperationalParameters:FileLockRetryDelayMs", 5000);

            // Create a combined cancellation token that respects both the user's cancellation and our timeout.
            using var timeoutCts = new CancellationTokenSource(TimeSpan.FromMinutes(timeoutMinutes));
            using var combinedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutCts.Token);

            // Loop indefinitely until the lock is acquired or the operation is cancelled/times out.
            while (true)
            {
                combinedCts.Token.ThrowIfCancellationRequested();
                FileStream? lockStream = null;
                try
                {
                    // Attempt to create a new file atomically. This will fail if the file already exists.
                    lockStream = new FileStream(lockFilePath, FileMode.CreateNew, FileAccess.Write, FileShare.None);
                    return lockStream; // Success.
                }
                catch (IOException)
                {
                    // This is the expected exception if the lock is already held.
                    lockStream?.Dispose();
                    _statusManager.Post("Waiting for another process to finish with the Power BI file...", MessageType.InProgress);
                    await Task.Delay(retryDelayMs, combinedCts.Token);
                }
                catch
                {
                    // For any other exception, ensure the stream is disposed and re-throw.
                    lockStream?.Dispose();
                    throw;
                }
            }
        }

        /// <summary>
        /// Gets the path to the weekly Power BI report file. This path is currently hardcoded but could be moved to configuration.
        /// </summary>
        /// <param name="username">The current system username, used to construct the path.</param>
        /// <returns>The full path to the weekly Power BI report file.</returns>
        private string GetWeeklyReportPath(string username)
        {
            // Use a different path for DEBUG and RELEASE builds to avoid modifying the production file during development.
#if DEBUG
            return $@"C:\Users\{username}\Harlow Printing\IT - Documents\PowerBI\Quote Conversion Report\Quotes conversion data_wrangled\weekly report quotes conversion merged - copy.xlsx";
#else
            return $@"C:\Users\{username}\Harlow Printing\IT - Documents\PowerBI\Quote Conversion Report\Quotes conversion data_wrangled\weekly report quotes conversion merged.xlsx";
#endif
        }

        #endregion

        #region Lead Time Analysis

        /// <summary>
        /// A public record to hold the extracted data for lead time analysis.
        /// This is public so it can be used by other services like the RetrospectiveAnalysisOrchestrator.
        /// </summary>
        public record LeadTimeRecord(
            string SourceFile,
            string CustomerName,
            string CustomerType,
            string EstimateNumber,
            string OrderNumber,
            decimal Value,
            DateTime EstimateDate,
            DateTime OrderDate,
            double LeadTimeCalendarDays,
            int LeadTimeBusinessDays
        );

        /// <summary>
        /// Creates the 'Lead Time Analysis' worksheet within an existing Excel package.
        /// This method orchestrates the extraction of data and generation of the summary sheet.
        /// </summary>
        /// <param name="package">The Excel package to which the new sheet will be added.</param>
        /// <param name="sourceDataSheetName">The name of the worksheet containing the source data.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
        private async Task CreateLeadTimeAnalysisSheetAsync(ExcelPackage package, string sourceDataSheetName, CancellationToken cancellationToken)
        {
            const string newSheetName = "Lead Time Analysis";
            _statusManager.Post($"Creating '{newSheetName}' sheet...", MessageType.InProgress);

            // Extract the lead time records from the 'DATA' sheet.
            var leadTimeEntries = await Task.Run(() => ExtractLeadTimeRecordsFromPackage(package, sourceDataSheetName), cancellationToken);

            // Create the new worksheet.
            var analysisSheet = package.Workbook.Worksheets.Add(newSheetName);

            // Generate the content of the new summary sheet.
            GenerateSummarySheet(analysisSheet, leadTimeEntries);

            _statusManager.Post($"'{newSheetName}' sheet created successfully.", MessageType.Success);
        }

        /// <summary>
        /// Extracts lead time records from a given worksheet within an Excel package.
        /// </summary>
        /// <param name="filePath">The path to the Excel file to process.</param>
        /// <returns>A list of LeadTimeRecord objects.</returns>
        public List<LeadTimeRecord> ExtractLeadTimeRecords(string filePath)
        {
            // This is a public entry point for external services like the RetrospectiveAnalyser.
            using var package = new ExcelPackage(new FileInfo(filePath));
            return ExtractLeadTimeRecordsFromPackage(package, Path.GetFileName(filePath));
        }

        /// <summary>
        /// Extracts lead time records from a given worksheet within an Excel package.
        /// </summary>
        /// <param name="package">The EPPlus ExcelPackage object to read from.</param>
        /// <param name="sourceFileName">The name of the original file, used for the SourceFile property.</param>
        /// <returns>A list of LeadTimeRecord objects.</returns>
        private List<LeadTimeRecord> ExtractLeadTimeRecordsFromPackage(ExcelPackage package, string sourceFileName)
        {
            var records = new List<LeadTimeRecord>();
            var dataSheet = package.Workbook.Worksheets["DATA"];
            if (dataSheet == null || dataSheet.Dimension == null) return records;

            // Map the required columns by their header names.
            var columnMap = MapColumnIndices(dataSheet, 1, new[] { "Customer", "Estimate No.", "Date", "Price", "Order Date", "Job No" });
            int endRow = dataSheet.Dimension.End.Row;

            // Iterate through each data row.
            for (int row = 2; row <= endRow; row++)
            {
                var orderDateValue = dataSheet.Cells[row, columnMap["Order Date"]].Value;
                var estimateDateValue = dataSheet.Cells[row, columnMap["Date"]].Value;

                // Process the row only if it has both an estimate date and an order date.
                if (TryGetDateTime(orderDateValue, out DateTime orderDate) && TryGetDateTime(estimateDateValue, out DateTime estimateDate))
                {
                    double leadTimeDays = (orderDate - estimateDate).TotalDays;
                    if (leadTimeDays >= 0)
                    {
                        // Extract all required data and create a new record.
                        string customerName = dataSheet.Cells[row, columnMap["Customer"]].Value?.ToString() ?? "N/A";
                        decimal.TryParse(dataSheet.Cells[row, columnMap["Price"]].Value?.ToString(), out decimal value);
                        records.Add(new LeadTimeRecord(
                            sourceFileName,
                            customerName,
                            GetCustomerType(customerName),
                            dataSheet.Cells[row, columnMap["Estimate No."]].Value?.ToString() ?? "N/A",
                            dataSheet.Cells[row, columnMap["Job No"]].Value?.ToString() ?? "N/A",
                            value,
                            estimateDate,
                            orderDate,
                            leadTimeDays,
                            CalculateBusinessDays(estimateDate, orderDate)
                        ));
                    }
                }
            }
            return records;
        }

        /// <summary>
        /// Generates the content for the lead time analysis summary sheet.
        /// </summary>
        /// <param name="worksheet">The Excel worksheet to write the summary to.</param>
        /// <param name="data">The list of lead time records to summarise.</param>
        public void GenerateSummarySheet(ExcelWorksheet worksheet, List<LeadTimeRecord> data)
        {
            // 1. Write Headers for the raw data section.
            worksheet.Cells["A1"].Value = "Source Report File";
            worksheet.Cells["B1"].Value = "Customer Name";
            worksheet.Cells["C1"].Value = "Customer Type";
            worksheet.Cells["D1"].Value = "Estimate Number";
            worksheet.Cells["E1"].Value = "Order Number";
            worksheet.Cells["F1"].Value = "Value";
            worksheet.Cells["G1"].Value = "Estimate Date";
            worksheet.Cells["H1"].Value = "Order Date";
            worksheet.Cells["I1"].Value = "Lead Time (Calendar Days)";
            worksheet.Cells["J1"].Value = "Lead Time (Business Days)";
            worksheet.Cells["A1:J1"].Style.Font.Bold = true;

            if (data.Any())
            {
                // 2. Write the main data body from the collection.
                worksheet.Cells["A2"].LoadFromCollection(data, false);

                // 3. Format the data columns.
                int dataRowCount = data.Count + 1;
                worksheet.Cells[2, 6, dataRowCount, 6].Style.Numberformat.Format = "£#,##0.00";
                worksheet.Cells[2, 7, dataRowCount, 8].Style.Numberformat.Format = "dd/MM/yyyy";
                worksheet.Cells[2, 9, dataRowCount, 10].Style.Numberformat.Format = "0.00";

                // 4. Generate the summary section with averages.
                int summaryStartRow = data.Count + 4;
                worksheet.Cells[summaryStartRow, 8].Value = "Summary of Averages";
                worksheet.Cells[summaryStartRow, 8, summaryStartRow, 10].Merge = true;
                worksheet.Cells[summaryStartRow, 8, summaryStartRow, 10].Style.Font.Bold = true;
                worksheet.Cells[summaryStartRow, 8, summaryStartRow, 10].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                summaryStartRow++;

                // Add summary table headers.
                worksheet.Cells[summaryStartRow, 7].Value = "Category";
                worksheet.Cells[summaryStartRow, 8].Value = "Avg. Calendar Days";
                worksheet.Cells[summaryStartRow, 9].Value = "Avg. Business Days";
                worksheet.Cells[summaryStartRow, 10].Value = "Avg. Value";
                worksheet.Cells[summaryStartRow, 7, summaryStartRow, 10].Style.Font.Italic = true;
                summaryStartRow++;

                // Group data by customer type and calculate averages for each group.
                var groupedData = data.GroupBy(d => d.CustomerType);
                foreach (var group in groupedData.OrderBy(g => g.Key))
                {
                    worksheet.Cells[summaryStartRow, 7].Value = group.Key;
                    worksheet.Cells[summaryStartRow, 8].Value = group.Average(g => g.LeadTimeCalendarDays);
                    worksheet.Cells[summaryStartRow, 9].Value = group.Average(g => g.LeadTimeBusinessDays);
                    worksheet.Cells[summaryStartRow, 10].Value = group.Average(g => g.Value);
                    summaryStartRow++;
                }

                // Add a separator line.
                worksheet.Cells[summaryStartRow, 7, summaryStartRow, 10].Style.Border.Top.Style = ExcelBorderStyle.Thin;
                summaryStartRow++;

                // Add Overall Averages.
                worksheet.Cells[summaryStartRow, 7].Value = "Overall Average";
                worksheet.Cells[summaryStartRow, 7].Style.Font.Bold = true;
                worksheet.Cells[summaryStartRow, 8].Value = data.Average(d => d.LeadTimeCalendarDays);
                worksheet.Cells[summaryStartRow, 9].Value = data.Average(d => d.LeadTimeBusinessDays);
                worksheet.Cells[summaryStartRow, 10].Value = data.Average(d => d.Value);
                worksheet.Cells[summaryStartRow, 8, summaryStartRow, 10].Style.Font.Bold = true;

                // Format the summary numbers.
                worksheet.Cells[summaryStartRow - groupedData.Count() - 1, 8, summaryStartRow, 9].Style.Numberformat.Format = "0.00";
                worksheet.Cells[summaryStartRow - groupedData.Count() - 1, 10, summaryStartRow, 10].Style.Numberformat.Format = "£#,##0.00";

                // 5. Add an explanatory note about business days.
                summaryStartRow += 2;
                worksheet.Cells[summaryStartRow, 1].Value = "Note: \"Business Days\" excludes Saturdays, Sundays, and all official England & Wales bank holidays.";
                worksheet.Cells[summaryStartRow, 1, summaryStartRow, 10].Merge = true;
            }

            // Auto-fit all columns for better readability.
            worksheet.Cells[worksheet.Dimension.Address].AutoFitColumns();
        }

        /// <summary>
        /// Calculates the number of business days between two dates, excluding weekends and bank holidays.
        /// </summary>
        /// <param name="startDate">The start date of the period.</param>
        /// <param name="endDate">The end date of the period.</param>
        /// <returns>The total number of business days.</returns>
        private int CalculateBusinessDays(DateTime startDate, DateTime endDate)
        {
            int businessDays = 0;
            // Iterate through each day in the period.
            for (var date = startDate.Date; date < endDate.Date; date = date.AddDays(1))
            {
                // If the day is not a weekend or a bank holiday, increment the counter.
                if (date.DayOfWeek != DayOfWeek.Saturday &&
                    date.DayOfWeek != DayOfWeek.Sunday &&
                    !BankHolidayHelper.IsBankHoliday(date))
                {
                    businessDays++;
                }
            }
            return businessDays;
        }

        /// <summary>
        /// Parses the customer type (e.g., "contract") from the customer name string.
        /// </summary>
        /// <param name="customerName">The full customer name string (e.g., "NHS Trust (Contract)").</param>
        /// <returns>The parsed customer type, or "non-contract" if not found.</returns>
        private string GetCustomerType(string customerName)
        {
            if (string.IsNullOrWhiteSpace(customerName)) return "Unknown";
            // Use a regular expression to find text within the last pair of parentheses.
            var match = Regex.Match(customerName, @"\(([^)]+)\)$");
            if (match.Success)
            {
                string type = match.Groups[1].Value.Trim().ToLowerInvariant();
                // Normalise "contract-direct" to "contract".
                return type == "contract-direct" ? "contract" : type;
            }
            return "non-contract";
        }

        /// <summary>
        /// Tries to convert a cell value from EPPlus into a DateTime object.
        /// It can handle native DateTime objects, doubles (OLE Automation Date), and standard string formats.
        /// </summary>
        /// <param name="excelCellValue">The value from the worksheet cell.</param>
        /// <param name="result">The resulting DateTime if conversion is successful.</param>
        /// <returns>True if conversion was successful, otherwise false.</returns>
        private bool TryGetDateTime(object? excelCellValue, out DateTime result)
        {
            result = DateTime.MinValue;
            if (excelCellValue == null) return false;
            if (excelCellValue is DateTime dt) { result = dt; return true; }

            string dateString = excelCellValue.ToString()!.Trim();
            if (string.IsNullOrWhiteSpace(dateString)) return false;

            // Try parsing as a number (OADate).
            if (double.TryParse(dateString, out double d) && d > 0) { result = DateTime.FromOADate(d); return true; }

            // Try parsing common string formats.
            if (DateTime.TryParseExact(dateString, "dd/MM/yyyy", CultureInfo.GetCultureInfo("en-GB"), DateTimeStyles.None, out result)) return true;
            return DateTime.TryParse(dateString, out result);
        }

        #endregion
    }
}
